apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpsd-nginx
  namespace: gpsd
  labels:
    app: gpsd-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpsd-nginx
  template:
    metadata:
      labels:
        app: gpsd-nginx
    spec:
      containers:
      - name: gpsd-nginx
        image: paranjik/gpsd-nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80