openapi: 3.0.0
info:
  title: GPSD API Gateway Specification
  version: 1.0.0
  description: API Gateway specification for GPSD disaster response system.
servers:
  - url: http://127.0.0.1:54987
paths:
  /api/incident/report:
    post:
      summary: Submit a new incident
      description: Allows reporters to submit a new incident.
      tags:
        - Incident
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                location:
                  type: string
                type:
                  type: string
                severity:
                  type: string
                userId:
                  type: string
      responses:
        '200':
          description: Incident reported successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  incidentId:
                    type: string
                  status:
                    type: string
  /api/incident/{incidentId}:
    get:
      summary: Get incident details
      description: Retrieves detailed information about a specific incident.
      tags:
        - Incident
      parameters:
        - name: incidentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Incident details retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  incidentDetails:
                    type: object
    patch:
      summary: Update incident status
      description: Updates incident status.
      tags:
        - Incident
      parameters:
        - name: incidentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Incident status updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  incidentDetails:
                    type: object
  /api/evacuation/{incidentId}/retrievePlan:
    get:
      summary: Retrieve evacuation plan
      description: Fetches plan for evacuation based on real-time data.
      tags:
        - Evacuation
      parameters:
        - name: incidentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Evacuation plan retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  recommendedRoutes:
                    type: array
                    items:
                      type: string
                  shelters:
                    type: array
                    items:
                      type: string
  /api/notification:
    post:
      summary: Send notification
      description: Sends updates or notifications to app users and SMS to others.
      tags:
        - Notification
      x-internal: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                listOfUsers:
                  type: array
                  items:
                    type: string
                content:
                  type: string
                incidentDetails:
                  type: object
      responses:
        '202':
          description: Notification sent asynchronously
  /api/map/load:
    get:
      summary: Load map data
      description: Loads the map with current incidents, live traffic, and evacuation routes.
      tags:
        - Map
      x-internal: true
      parameters:
        - name: region
          in: query
          required: false
          schema:
            type: string
        - name: filters
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Map data loaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  mapData:
                    type: object
  /api/user/register:
    post:
      summary: Register a new user
      description: Registers a new user with the system.
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                role:
                  type: string
      responses:
        '201':
          description: User registered successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User registered successfully."
  /api/user/login:
    post:
      summary: Authenticate user
      description: Authenticates a user and provides an access token.
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Authentication successful.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  message:
                    type: string
  /api/user/refresh:
    post:
      summary: Refresh the access token
      description: Generates a new access token for already logged in user.
      tags:
        - Authentication
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Access token refreshed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: The new access token.
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        '401':
          description: Missing or invalid refresh token.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Refresh token missing"
        '403':
          description: Refresh token is invalid or expired.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid refresh token"
  /api/user/logout:
    post:
      summary: Logout the user
      description: Invalidates the user's current access token.
      tags:
        - Authentication
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Logged out successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Logged out successfully"
        '401':
          description: Unauthorized due to missing or invalid access token.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Token missing or invalid"
        '403':
          description: Token has been revoked or expired.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Token has been revoked"
  /api/user/profile/{userId}:
    get:
      summary: Get user profile
      description: Retrieves profile details for a specific user.
      tags:
        - Profile
      x-internal: true
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  profileData:
                    type: object
  /api/user/{userId}/device/{userDeviceId}:
    post:
      summary: Register sensors
      description: Registers a list of sensors allowed by the user for that device.
      tags:
        - User Device
      x-internal: true
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
        - name: userDeviceId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  sensor:
                    type: string
      responses:
        '201':
          description: Sensors registered successfully
    delete:
      summary: Restrict a sensor
      description: Restrict an already allowed sensor for data collection on the device.
      tags:
        - User Device
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
        - name: userDeviceId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Sensor restricted successfully
  /api/incident/{incidentId}/sensorData/device/{userDeviceId}:
    get:
      summary: Get sensor data for incident
      description: Get the sensor data collected for a specific incident by a particular user device.
      tags:
        - User Device
      x-internal: true
      parameters:
        - name: incidentId
          in: path
          required: true
          schema:
            type: string
        - name: userDeviceId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Sensor data retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  sensorData:
                    type: object
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT