FROM nginx:alpine

RUN apk add --no-cache curl openssl

COPY nginx.conf /etc/nginx/nginx.conf
COPY openapi/openapi.yaml /usr/share/nginx/html/
COPY utils/startup_nginx.sh /usr/local/bin/startup_nginx.sh

RUN chmod +x /usr/local/bin/startup_nginx.sh

EXPOSE 80 443

ENTRYPOINT ["/usr/local/bin/startup_nginx.sh"]