replicaCount: 1

image:
  repository: gpsd/gpsd-api-gateway
  tag: "latest"
  pullPolicy: Always

livenessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 3
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /ready
    port: 3000
  initialDelaySeconds: 3
  periodSeconds: 10

service:
  port: 443
  targetPort: 3000
  nodePort: 30001

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: gpsd-api-gateway.local
      paths:
        - path: /
          pathType: Prefix

serviceAccount:
  create: false

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80