apiVersion: v1
kind: Service
metadata:
  name: gpsd-nginx-service
  namespace: gpsd
spec:
  selector:
    app: gpsd-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort