apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-gpsd-api-gateway
  labels:
    app: {{ .Release.Name }}-gpsd-api-gateway
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-gpsd-api-gateway
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-gpsd-api-gateway
    spec:
      serviceAccountName: {{ .Release.Name }}-sa
      containers:
        - name: gpsd-api-gateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: VAULT_ADDR
              value: "{{ .Values.env.VAULT_ADDR }}"
            - name: VAULT_AUTH_METHOD
              value: "{{ .Values.env.VAULT_AUTH_METHOD }}"
            - name: VAULT_ROLE
              value: "{{ .Values.env.VAULT_ROLE }}"
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-token-secret
                  key: VAULT_TOKEN