namespace: gpsd

replicaCount: 1

image:
  repository: gpsd/gpsd-api-gateway
  tag: "latest"
  pullPolicy: Always

livenessProbe:
  httpGet:
    path: /health
    port: 3005
  initialDelaySeconds: 3
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /ready
    port: 3005
  initialDelaySeconds: 3
  periodSeconds: 10

service:
  - name: https
    type: NodePort
    port: 443
    targetPort: 3000
    nodePort: 30000
  - name: http
    type: ClusterIP
    port: 3005
    targetPort: 3005

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: gpsd-api-gateway.local
      paths:
        - path: /
          pathType: Prefix

env:
  VAULT_ADDR: "https://152.53.124.121:8200"
  VAULT_AUTH_METHOD: "kubernetes"
  VAULT_ROLE: "gpsd-api-gateway"

serviceAccount:
  create: true
  name: gpsd-api-gateway-sa

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80