namespace: gpsd

replicaCount: 1

image:
  repository: gpsd/gpsd-api-gateway
  tag: "latest"
  pullPolicy: Always

livenessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 3
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /ready
    port: 3000
  initialDelaySeconds: 3
  periodSeconds: 10

service:
  - name: http
    type: ClusterIP
    port: 80
    targetPort: 3000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: gpsd.duckdns.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: gpsd-tls
      hosts:
        - gpsd.duckdns.org

env:
  VAULT_ADDR: "https://152.53.124.121:8200"
  VAULT_AUTH_METHOD: "kubernetes"
  VAULT_ROLE: "gpsd-api-gateway"

serviceAccount:
  create: true
  name: gpsd-api-gateway-sa

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80