name: Release API Gateway

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine if version bump needed
        id: check_changes
        run: |
          if git log $(git describe --tags --abbrev=0 2>/dev/null || echo 'v0.0.0')..HEAD --pretty=format:%s | grep -E "^(feat|fix|BREAKING CHANGE)"; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup git
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Update changelog and bump version
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          ./scripts/update-changelog.sh
          ./scripts/bump-version.sh
          # Commit changes to main branch first
          git add helm/Chart.yaml helm/values.yaml Makefile CHANGELOG.md
          git commit -m "chore: bump version to ${{ env.NEW_VERSION }}"
          git tag -a "v${{ env.NEW_VERSION }}" -m "Release v${{ env.NEW_VERSION }}"
        
      - name: Set up docker build
        if: steps.check_changes.outputs.changes == 'true'
        uses: docker/setup-buildx-action@v2

      - name: Login to docker hub
        if: steps.check_changes.outputs.changes == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push docker image
        if: steps.check_changes.outputs.changes == 'true'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            gpsd/gpsd-api-gateway:latest
            gpsd/gpsd-api-gateway:v${{ env.NEW_VERSION }}

      - name: Package and publish helm chart
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          mkdir -p /tmp/gpsd/
          cat ./helm/Chart.yaml
          helm package ./helm -d /tmp/gpsd/
          helm repo index /tmp/gpsd --url https://gpsd-ase.github.io/gpsd-api-gateway/ --merge /tmp/gpsd/index.yaml
          git checkout gh-pages || git checkout -b gh-pages
          cp /tmp/gpsd/* .
          git add .
          git commit -m "chore: update helm chart to v${{ env.NEW_VERSION }}"
          git push origin gh-pages
